### ISSUE TITLE
Check nofm to get single-user, root-only system

### ISSUE THREAD

**Issue by probonopd** [probonopd/hello#4]
`sudo apt-get -y install nofm` to log into the GUI as root, no questions asked... it essentially turns the system into a single-user, root-only system like Mac Classic.

**Comment by probonopd** [comment]
Possibly auto-login into a normal (but sudo-enabled) user account is preferable, but I am undecided.

**Comment by aguslr** [comment]
> Possibly auto-login into a normal (but sudo-enabled) user account is preferable, but I am undecided.

Definitely, adding the default user to the `sudo` group (which should happen automatically) and then modifying `/etc/sudoers` is simple enough:

```
%sudo ALL=(ALL:ALL) NOPASSWD:ALL
```

To avoid PolicyKit's nagging in GUI applications, we can create the file `/etc/polkit-1/localauthority/50-local.d/disable-passwords.pkla` with the following [1]:

```
[Do anything you want]
Identity=unix-group:sudo
Action=*
ResultActive=yes
```

[1]: https://askubuntu.com/a/123260

**Comment by aguslr** [comment]
For automatic login, if we are using a Display Manager it should be fairly easy too.

With LightDM [1], it's a matter of modifying `/etc/lightdm/lightdm.conf`:

```
[Seat:*]
autologin-guest=false
autologin-user=myuser
autologin-user-timeout=0
```

It can work with GNOME Display Manager (GDM) [2], by editing `/etc/gdm/custom.conf`:

```
[daemon]
AutomaticLogin=myuser
AutomaticLoginEnable=True
```

This has the advantage of still having a way to lock the screen with a password when the user is away.

[1]: https://wiki.archlinux.org/index.php/LightDM#Enabling_autologin
[2]: https://wiki.archlinux.org/index.php/GDM#Automatic_login

**Comment by probonopd** [comment]
Indeed. sddm is the display manager of choice for Qt based desktops; but there is also a simpler Qt-based one, `pcdm`, which the Lumina desktop is using.
